# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf0434d757d08da25ccb444adc472e1d99a74bdd77c0de85093e3d500f67f079ca0b09987e644215eed9a1de78228756f0cda5251d53aee2d11257442f1cb415

test:
  secret_key_base: 131083329737e4c12fae4619e6b3fe9e6d2aa55841d9b158c20fa44ae04230608f659ac6a97a3714b9fe716a92a5f8a8414d8f4b86606f1c19df9b346546fc71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
